import { Component } from '@angular/core';

@Component({
  selector: 'app-product-details',
  templateUrl: './product-details.component.html',
  styleUrl: './product-details.component.scss'
})
export class ProductDetailsComponent {


  products = [
    {
      title: 'HAVIT HV-G92 Gamepad',
      price: 120,
      actualPrice: 200,
      discount: '-40%',
      rating: 2,
      heartIcon: 'heart.png',
      eyeIcon: 'eye.png',
      productImage: 'joystick.png',
      starIcon: 'star.png',
      percentage: 80,
    },
    {
      title: 'HAVIT HV-G92 Keyboard',
      price: 120,
      actualPrice: 200,
      discount: '-40%',
      rating: 4,
      heartIcon: 'heart.png',
      eyeIcon: 'eye.png',
      productImage: 'keyboard.png',
      starIcon: 'star.png',
      percentage: 80,
    },
    {
      title: 'HAVIT HV-G92 Monitor',
      price: 120,
      actualPrice: 200,
      discount: '-40%',
      rating: 3,
      heartIcon: 'heart.png',
      eyeIcon: 'eye.png',
      productImage: 'monitor.png',
      starIcon: 'star.png',
      percentage: 80,
    },
    {
      title: 'HAVIT HV-G92 Monitor',
      price: 120,
      actualPrice: 200,
      discount: '-40%',
      rating: 3,
      heartIcon: 'heart.png',
      eyeIcon: 'eye.png',
      productImage: 'monitor.png',
      starIcon: 'star.png',
      percentage: 80,
    },
    {
      title: 'HAVIT HV-G92 Chair',
      price: 120,
      actualPrice: 200,
      discount: '-40%',
      rating: 2,
      heartIcon: 'heart.png',
      eyeIcon: 'eye.png',
      productImage: 'chair.png',
      starIcon: 'star.png',
      percentage: 80,
    },
    {
      title: 'HAVIT HV-G92 Gamepad',
      price: 120,
      actualPrice: 200,
      discount: '-40%',
      rating: 2,
      heartIcon: 'heart.png',
      eyeIcon: 'eye.png',
      productImage: 'joystick.png',
      starIcon: 'star.png',
      percentage: 80,
    },
    {
      title: 'HAVIT HV-G92 Keyboard',
      price: 120,
      actualPrice: 200,
      discount: '-40%',
      rating: 4,
      heartIcon: 'heart.png',
      eyeIcon: 'eye.png',
      productImage: 'keyboard.png',
      starIcon: 'star.png',
      percentage: 80,
    },
    {
      title: 'HAVIT HV-G92 Monitor',
      price: 120,
      actualPrice: 200,
      discount: '-40%',
      rating: 3,
      heartIcon: 'heart.png',
      eyeIcon: 'eye.png',
      productImage: 'monitor.png',
      starIcon: 'star.png',
      percentage: 80,
    },
    {
      title: 'HAVIT HV-G92 Monitor',
      price: 120,
      actualPrice: 200,
      discount: '-40%',
      rating: 3,
      heartIcon: 'heart.png',
      eyeIcon: 'eye.png',
      productImage: 'monitor.png',
      starIcon: 'star.png',
      percentage: 80,
    },
    {
      title: 'HAVIT HV-G92 Chair',
      price: 120,
      actualPrice: 200,
      discount: '-40%',
      rating: 2,
      heartIcon: 'heart.png',
      eyeIcon: 'eye.png',
      productImage: 'chair.png',
      starIcon: 'star.png',
      percentage: 80,
    },
    {
      title: 'HAVIT HV-G92 Chair',
      price: 120,
      actualPrice: 200,
      discount: '-40%',
      rating: 2,
      heartIcon: 'heart.png',
      eyeIcon: 'eye.png',
      productImage: 'chair.png',
      starIcon: 'star.png',
      percentage: 80,
    },
  ];
  gameData: any = {
    title1: "Related Item",

  };
}
